---
title: "Estadísticas policiales de Costa Rica 2025"
author: "Alexa Lobo Díaz"
format: html
lang: es
toc: true 
theme: cayman
---

```{r}

#| label: cargar-paquetes
#| warning: false
#| message: false
#| echo: false

library(tidyverse)
library(knitr)
```

```{r}
#| label: cargar-datos
#| echo: false

estadisticas <- read.csv("estadisticaspoliciales2025.csv")

```


# Introducción

Este documento muestra estadísticas policiales de Costa Rica para el año 2025.

# Exploración inicial de datos

## Estructura de los datos 

```{r}
#| label: mostrar-estructura-datos
#| code-fold: true
estadisticas |>  glimpse()
```
## Muestra de los datos 

```{r}

#| label: mostrar-datos
#| code-fold: true
estadisticas |>
  slice_head(n = 5) |>
  kable()
```

# Análisis de datos


## Conteo de los tipos de delito 

```{r}

#| label: Conteo-tipo-delitos
#| code-fold: true

#estadisticas |>
 # group_by(Delito) |>
 # summarize(n = n()) |>
 # arrange(desc(n)) |>
 # kable()

estadisticas |> 
  count(Delito, SubDelito) |> 
  arrange (Delito, SubDelito) |>
  kable()
```

## Cantidad de delitos por provincia

```{r}
#| label: cantidad-delitos-provincia
#| code-fold: true

estadisticas |>
  count( Provincia) |>
  arrange(desc(n)) |>
  kable()
  
```


## Cantidad de homcidios por provincia, cantón, distrito


```{r}
#| label: cantidad-homicidios-provincia-cantón-distrito
#| code-fold: true

estadisticas |> 
  filter(Delito == "HOMICIDIO") |>
  count(Provincia, Canton, Distrito) |>
  arrange(desc(n)) |>
  slice_head(n =20) |>
  kable()
```





